-- 001_init.sql
-- Initial schema for the wedding missions app.
-- Mirrors the shapes in lib/data/wedding-data.js so the seed maps 1:1.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Keep updated_at fresh on any row change.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- guests
-- ---------------------------------------------------------------------------
-- id is text so seed rows can keep readable slugs ("guest-nadya") while
-- CSV-imported rows get gen_random_uuid()::text.
-- phone holds whatever the CSV provides; phone_last4 is derived for the
-- onboarding "last 4 digits" claim check.
-- session_epoch is embedded in the guest session cookie; an admin "reset
-- claim" bumps it, which invalidates any cookie already handed out.
CREATE TABLE guests (
  id            text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name          text NOT NULL,
  phone         text,
  phone_last4   text GENERATED ALWAYS AS (
                  NULLIF(right(regexp_replace(coalesce(phone, ''), '\D', '', 'g'), 4), '')
                ) STORED,
  "table"       text,
  relation      text,
  hometown      text,
  claimed_at    timestamptz,
  session_epoch integer NOT NULL DEFAULT 0,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX guests_name_lower_idx ON guests (lower(name));
CREATE INDEX guests_phone_last4_idx ON guests (phone_last4);

CREATE TRIGGER guests_set_updated_at
  BEFORE UPDATE ON guests
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- missions  (the card-deck content)
-- ---------------------------------------------------------------------------
CREATE TABLE missions (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kicker      text NOT NULL,
  title       text NOT NULL,
  note        text,
  points      integer NOT NULL DEFAULT 0 CHECK (points >= 0),
  kind        text NOT NULL CHECK (kind IN ('photo', 'text')),
  color       text NOT NULL CHECK (color IN ('coral', 'butter', 'blue', 'sage', 'lilac', 'rose')),
  sort_order  integer NOT NULL DEFAULT 0,
  active      boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX missions_active_sort_idx ON missions (active, sort_order);

CREATE TRIGGER missions_set_updated_at
  BEFORE UPDATE ON missions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- submissions  (a guest's answer to a mission; feeds the wall + leaderboard)
-- ---------------------------------------------------------------------------
-- Every submission starts life as 'pending'. approved / rejected are only
-- ever surfaced in the admin backoffice; the public wall shows 'approved'
-- only. points is a snapshot of the mission's points at submission time so
-- later edits to the mission don't retroactively rescore guests.
-- Scoring rule: points count while status <> 'rejected' (apply on submit,
-- an admin rejection deducts them).
CREATE TABLE submissions (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  guest_id    text NOT NULL REFERENCES guests(id) ON DELETE CASCADE,
  mission_id  bigint NOT NULL REFERENCES missions(id) ON DELETE RESTRICT,
  kind        text NOT NULL CHECK (kind IN ('photo', 'text')),
  body        text,
  media_url   text,
  media_type  text,
  points      integer NOT NULL DEFAULT 0,
  status      text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  CONSTRAINT submissions_has_content CHECK (body IS NOT NULL OR media_url IS NOT NULL)
);

CREATE INDEX submissions_status_created_idx ON submissions (status, created_at DESC);
CREATE INDEX submissions_guest_idx ON submissions (guest_id);
CREATE INDEX submissions_mission_idx ON submissions (mission_id);

-- ---------------------------------------------------------------------------
-- guest_scores  (derived leaderboard view)
-- ---------------------------------------------------------------------------
CREATE VIEW guest_scores AS
SELECT
  g.id   AS guest_id,
  g.name AS name,
  COALESCE(SUM(s.points) FILTER (WHERE s.status <> 'rejected'), 0)::int AS points,
  COUNT(s.id) FILTER (WHERE s.status = 'pending')::int  AS pending_count,
  COUNT(s.id) FILTER (WHERE s.status = 'approved')::int AS approved_count
FROM guests g
LEFT JOIN submissions s ON s.guest_id = g.id
GROUP BY g.id, g.name;

-- ---------------------------------------------------------------------------
-- auth_attempts  (throttle the 4-digit claim check)
-- ---------------------------------------------------------------------------
-- "Light touch": a small fixed delay per wrong attempt is applied in code;
-- a name hard-locks only after ~20 failures. locked_until gates the check.
CREATE TABLE auth_attempts (
  guest_id        text PRIMARY KEY REFERENCES guests(id) ON DELETE CASCADE,
  failed_count    integer NOT NULL DEFAULT 0,
  locked_until    timestamptz,
  last_attempt_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- guest_progress  (per-guest UI convenience state; card position in the deck)
-- ---------------------------------------------------------------------------
CREATE TABLE guest_progress (
  guest_id      text PRIMARY KEY REFERENCES guests(id) ON DELETE CASCADE,
  mission_index integer NOT NULL DEFAULT 0,
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER guest_progress_set_updated_at
  BEFORE UPDATE ON guest_progress
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
